# Generated by Django 5.1 on 2024-08-25 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='streaming_list',
        ),
        migrations.RemoveField(
            model_name='streaminglist',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='streaminglist',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='streaminglist',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.CreateModel(
            name='StreamingListMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.movie')),
                ('streaming_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.streaminglist')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('streaming_list', 'movie')},
            },
        ),
        migrations.AddField(
            model_name='streaminglist',
            name='movies',
            field=models.ManyToManyField(through='torrents.StreamingListMovie', to='torrents.movie'),
        ),
    ]
