# Generated by Django 4.2 on 2024-08-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0003_alter_movie_imdb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
