# Generated by Django 4.2 on 2024-09-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0005_alter_movie_mdblist_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mediatype',
            field=models.CharField(default='movie', max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_year',
            field=models.IntegerField(default=0),
        ),
    ]
