# Generated by Django 4.2 on 2024-09-27 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0009_episode_tvshow_tvshowwatchhistory_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVShowStreamingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TVShowStreamingListShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('streaming_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.tvshowstreaminglist')),
                ('tv_show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torrents.tvshow')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='tvshowstreaminglist',
            name='tv_shows',
            field=models.ManyToManyField(through='torrents.TVShowStreamingListShow', to='torrents.tvshow'),
        ),
    ]
