# Generated by Django 4.2 on 2024-10-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0010_tvshowstreaminglist_tvshowstreaminglistshow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base_url', models.URLField()),
                ('has_tv_shows', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('uses_tmdb', models.BooleanField(default=True)),
                ('movie_path', models.CharField(blank=True, max_length=255)),
                ('tv_show_path', models.CharField(blank=True, max_length=255)),
                ('season_placeholder', models.CharField(default='{season}', max_length=20)),
                ('episode_placeholder', models.CharField(default='{episode}', max_length=20)),
            ],
        ),
    ]
