# Generated by Django 4.2 on 2024-10-19 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torrents', '0011_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='imdb_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
